# Generated by Django 4.1.4 on 2022-12-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_injection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
